services:
  tonk-server:
    image: tonklabs/tonk-server:latest
    container_name: tonk-server
    volumes:
      - tonk-data:/app/stores
      - tonk-bundles:/app/bundles
      - ./dist:/tmp/app-bundle # Mount the local dist directory to copy into the container
    ports:
      - "7777:7777" # Tonk server port
      - "8000:8000" # Default port for the first bundle
    environment:
      - PORT=7777
    restart: unless-stopped
    # This command installs curl, starts the Tonk server and then deploys and starts the app bundle
    command: >
      sh -c "
        # Install curl if not already installed
        echo 'Installing curl...'
        apk add curl

        # Start Tonk server in the background
        echo 'Starting Tonk server...'
        tsx src/docker-start.ts &
        
        # Wait for the server to be ready
        echo 'Waiting for Tonk server to start...'
        until $(curl --output /dev/null --silent --fail http://localhost:7777/ping); do
          printf '.'
          sleep 1
        done
        echo 'Tonk server is up!'
        
        # Create a tarball from the mounted dist directory
        echo 'Creating app bundle...'
        cd /tmp
        tar -czf app-bundle.tar.gz -C /tmp/app-bundle .
        
        # Upload the bundle to the Tonk server
        echo 'Uploading app bundle to Tonk server...'
        curl -X POST -F 'bundle=@/tmp/app-bundle.tar.gz' -F 'name=tonk-app' http://localhost:7777/upload-bundle
        
        # Start the bundle
        echo 'Starting app bundle...'
        curl -X POST -H 'Content-Type: application/json' -d '{\"bundleName\":\"tonk-app\",\"port\":8000}' http://localhost:7777/start
        
        # Keep the container running
        tail -f /dev/null
      "

volumes:
  tonk-data:
  tonk-bundles:
